### ISSUE TITLE
Feedback from Joel

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_9_solar-savers#86]
Major:
- [x] Include setup cost of panels?
- [x] Include how many panels of different types to fit into a roof
- [x] Be more granular in efficiency to more accurately reflect cost
- [x] Zoom in / filter map data so that only one province is shown. And then highlight point for selected city.

Minor:
- [ ] Maybe consider 10 years savings instead of yearly?
- [x] Remove double border on energy save, and stack horizontally
- [x] General color schemes and title layouts
- [x] Background for widgets and panel comparison should be separated as two clearer areas.

**Comment by nicolebid** [comment]
Implemented payback period instead of 10yr savings
