### ISSUE TITLE
Feedback from @tonyshumlh

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/DSCI-532_2024_9_solar-savers#89]
#### Documentation

The package includes all the following forms of documentation:

- [X] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README.
- [x] **Installation instructions:** for the development version of the package and any non-standard dependencies in README.
- [x] **Vignette(s)** demonstrating major functionality that runs successfully locally.
- [X] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING.

Readme file  requirements
The package meets the readme requirements below:

- [X] Package has a README.md file in the root directory.

The README should include, from top to bottom:

- [X] The package name
- [X] Short description of package goals.
- [X] Package installation instructions
- [ ] Any additional setup required to use the package (authentication tokens, etc.)
- [X] Descriptive links to all vignettes. If the package is small, there may only be a need for one vignette which could be placed in the README.md file.
    - [X] Brief demonstration of package usage (as it makes sense - links to vignettes could also suffice here if package description is clear)
- [ ] If applicable, how the package compares to other similar packages and/or how it relates to other packages in the scientific ecosystem.
- [X] Citation information

#### Usability
Reviewers are encouraged to submit suggestions (or pull requests) that will improve the usability of the package as a whole.
Package structure should follow general community best-practices. In general please consider whether:

- [X] Package documentation is clear and easy to find and use.
- [X] The need for the package is clear
- [ ] All functions have documentation and associated examples for use
- [X] The package is easy to install

#### Functionality

- [X] **Installation:** Installation succeeds as documented.
- [X] **Functionality:** Any functional claims of the software been confirmed.
- [X] **Performance:** Any performance claims of the software been confirmed.

#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing:
2 hours
---

#### Review Comments
- [x] All functions are written into app.py, which can be further modularized for easier maintenance and development.
- [ ] The functions lack docstring that describes the functions' usage, which should help collaborators for better understanding
- [x] The geo-map in the dashboard seems does not change with the widget selection. Also, there is no reaction for clicking the bubble on the map either. Is it expected? I recommend changing the map according to the user selection in province and region.
- [x] The combination of figures and widgets in the layout can be improved as now the widgets on the top left control the figures on bottom right, while the widgets on bottom left control the figures on bottom left. The widgets and the corresponding figures can be grouped together within the same area of the dashboard.
- [x] It seems the "Difference in Savings" only includes the first 2 choices in "Panel Comparison". Is it expected? It can be modified in tabular form to illustrate the difference in saving for each pair within the selections.
- [ ] Apart from money saving, the corresponding energy saving might also be added in the Chart "Difference in Savings" for consumer to compare the potential environmental impact among different panel efficiencies.
- The dashboard and its widgets are intuitive to use.
- The update of the charts is very fast and stable!

**Comment by nicolebid** [comment]
Thanks for the suggestions and helpful feedback! We have not implemented unchecked tasks in Review Comments due to time restraints.
